chimpcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('chimps/', views.chimps_index, name='index'),
    path('chimps/<int:chimp_id>', views.chimps_detail, name='detail'),
    path('chimps/create/', views.ChimpCreate.as_view(), name='chimps_create'),
    path('chimps/<int:pk>/update', views.ChimpUpdate.as_view(), name='chimps_update'),
    path('chimps/<int:pk>/delete', views.ChimpDelete.as_view(), name='chimps_delete'),
    path('chimps/<int:chimp_id>/add_shift/', views.add_shift, name='add_shift'),
    path('chimps/<int:chimp_id>/assoc_slingshot/<int:slingshot_id>/', views.assoc_slingshot, name='assoc_slingshot'),
    path('chimps/<int:chimp_id/unassoc_slingshot/<int:toy_id>/', views.unassoc_shlingshot, name='unassoc_toy'),
    path('slingshots/', views.SlingshotList.as_view(), name='slingshots_index'),
    path('slingshots/<int:pk>/', views.SlingshotDetail.as_view(), name='slingshot_detail'),
    path('slingshots/create/', views.SlingshotCreate.as_view(), name='slingshots_create'),
    path('slingshots/<int:pk>/update', views.SlingshotUpdate.as_view(), name='slingshots_update'),
    path('slingshots/<int:pk>/delete', views.SlingshotDelete.as_view(), name='slingshots_delete')
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

SHIFTSEGS = (
    ('1','1st shift'),
    ('2','2nd shift'),
    ('3','3rd shift')
)
AMMOT = (
    ('T','Tracer Rounds'),
    ('HS','Hog Scatter Shot'),
    ('BP','Bristle Piercing Rounds')
)

class Slingshot(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)
    ammo = models.CharField(
        max_length=1,
        choices=AMMOT,
        default=AMMOT[0][0]
    )

class Chimp(models.Model):
    name = models.CharField(max_length=100)
    weight = models.IntegerField()
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    slingshots = models.ManyToManyField(Slingshot)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'chimp_id': self.id})

class Shift(models.Model):
    date = models.DateField('shift date')
    shiftSeg = models.CharField(
        max_length=1,
        choices=SHIFTSEGS,
        default=SHIFTSEGS[0][0]
        )

    chimp = models.ForeignKey(Chimp, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_shiftSeg_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Shift

class ShiftForm(ModelForm):
    class Meta:
        model = Shift
        fields = ['date','shiftSeg']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Chimp, Slingshot
from .forms import ShiftForm

# Create your views here.
class  ChimpCreate(CreateView):
    model = Chimp
    fields = '__all__'
    

class ChimpUpdate(UpdateView):
    model = Chimp
    fields = ['weight', 'description', 'age']

class ChimpDelete(DeleteView):
    model = Chimp
    success_url = '/chimps/'

def home(request):
    return render(request, 'home.html/')

def about(request):
    return render(request, 'about.html')

def chimps_index(request):
    chimps = Chimp.objects.all()
    return render(request, 'chimps/index.html', { 'chimps': chimps })

def chimps_detail(request, chimp_id):
    chimp = Chimp.objects.get(id=chimp_id)
    slingshots_chimp_doesnt_carry = Slingshot.objects.exclude(id__in = chimp.slingshots.all().values_list('id'))
    shift_form = ShiftForm()
    return render(request, 'chimps/detail.html', { 'chimp': chimp, 
        'shift_form': shift_form,  'slingshots': slingshots_chimp_doesnt_carry
        })

def add_shift(request, chimp_id):
    form = ShiftForm(request.POST)
    if form.is_valid():
        new_shift = form.save(commit=False)
        new_shift.chimp_id = chimp_id
        new_shift.save()
    return redirect('detail', chimp_id=chimp_id)

def assoc_slingshot(request, chimp_id, slingshot_id):
    Chimp.objects.get(id=chimp_id).slingshots.add(slingshot_id)
    return redirect('detail', chimp_id=chimp_id)

def unassoc_shlingshot(request, chimp_id, slingshot_id):
    Chimp.objects.get(id=chimp_id).slingshots.remove(slingshot_id)
    return redirect('detail', chimp_id=chimp_id)

class SlingshotList(ListView):
    model = Slingshot

class SlingshotDetail(DetailView):
    model = Slingshot

class SlingshotCreate(CreateView):
    model = Slingshot
    fields = '__all__'

class SlingshotUpdate(UpdateView):
    model = Slingshot
    fields = ['name','color','ammo']

class SlingshotDelete(DeleteView):
    model = Slingshot
    success_url = '/slingshots/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content%}
    <h1>About Chimp Security</h1>
    <hr />
    <p>If you a have a nasty feral hog problem, Chimp security is your solution.</p>
    <footer>All Rights Reserved, &copy; 2019 Chimp Security</footer>
    
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Chimp Security</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;ChimpSecurity</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'chimps_create' %}">Add a Chimp</a></li>
          <li><a href="{% url 'index' %}">View Available Chimps</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Chimp Security &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/chimps/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Chimp Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ chimp.name }}</span>
                <p>Weight {{ chimp.weight }}.lbs</p>
                <p>Description: {{ chimp.description }}</p>
                <p>Age: {{ chimp.age }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'chimps_update' chimp.id %}">Edit</a>
                <a href="{% url 'chimps_delete' chimp.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_shift' chimp.id %}" method="post">
            {% csrf_token %}
            {{ shift_form.as_p }}
            <input type="submit" class="btn" value="Add Shift">
        </form>
        <table class="striped">
            <thead>
                <tr><th>Date</th><th>Shift</th></tr>
            </thead>
            <tbody>
                {% for shift in chimp.shift_set.all %}
                    <tr>
                        <td>{{shift.date}}</td>
                        <td>{{shift.get_shiftSeg_display}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    var selectEl = document.getElementById('id_shiftSeg');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/chimps/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Chimp List</h1>

{% for chimp in chimps %}
    <div class="card">
        <a href="{% url 'detail' chimp.id %}">
        <div class="card-content">
            <span class="card-title">{{ chimp.name }}</span>
            <p>{{ chimp.weight }}.lbs</p>
            <p>Description: {{ chimp.description }}</p>
            {% if chimp.age > 0 %}
                <p>Age: {{ chimp.age }}</p>
            {% else %}
                <p>Age: Chimpitten</p>
            {% endif %}
        </div>
    </a>
    </div>

{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}


<h1>Home</h1>


{% endblock %}

main_app/templates/main_app/chimp_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Chimp</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' chimp.id %}">Cancel</a>
    </form>
    {% endblock %}

main_app/templates/main_app/chimp_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit<span class="teal-text"> {{object.name}}</span></h1>
    {% else %}
        <h1>Add Chimp</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}

        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}